import type { AgentDefinition } from '../types/core'

export const agentRegistry: AgentDefinition[] = [
  {
    id: 'research-coordinator',
    name: 'Research Coordinator',
    domain: 'terra',
    responsibility: 'Coordinates Terra AOI and tool chain execution.',
    allowedToolCategories: ['terra', 'verification'],
    readWrite: 'read',
    verificationRequirements: ['Evidence verifier review required for alerts'],
  },
  {
    id: 'source-scout',
    name: 'Source Scout',
    domain: 'terra',
    responsibility: 'Finds external data sources and observations.',
    allowedToolCategories: ['terra'],
    readWrite: 'read',
    verificationRequirements: ['Provider provenance required'],
  },
  {
    id: 'eo-analyst',
    name: 'EO Analyst',
    domain: 'terra',
    responsibility: 'Assesses Earth observation indicators.',
    allowedToolCategories: ['terra', 'verification'],
    readWrite: 'read',
    verificationRequirements: ['Confidence and uncertainty reporting required'],
  },
  {
    id: 'hazard-agent',
    name: 'Hazard Agent',
    domain: 'terra',
    responsibility: 'Produces preliminary risk alerts only.',
    allowedToolCategories: ['terra', 'verification'],
    readWrite: 'read',
    verificationRequirements: ['Never output verified finding without verification checks'],
  },
  {
    id: 'evidence-verifier',
    name: 'Evidence Verifier',
    domain: 'verification',
    responsibility: 'Assigns PASS/WARNING/FAIL/INSUFFICIENT_DATA verification state.',
    allowedToolCategories: ['verification'],
    readWrite: 'read',
    verificationRequirements: ['Must include uncertainties and missing evidence'],
  },
  {
    id: 'game-coordinator',
    name: 'Game Coordinator',
    domain: 'cube',
    responsibility: 'Coordinates cube AI experiment workflows.',
    allowedToolCategories: ['cube', 'verification'],
    readWrite: 'write',
    verificationRequirements: ['Human approval required for promotion'],
  },
  {
    id: 'qa-agent',
    name: 'QA Agent',
    domain: 'cube',
    responsibility: 'Runs tests and legality checks.',
    allowedToolCategories: ['cube', 'system'],
    readWrite: 'read',
    verificationRequirements: ['Regression status must be explicit'],
  },
  {
    id: 'visual-agent',
    name: 'Visual Agent',
    domain: 'visual',
    responsibility: 'Proposes reversible visual improvements.',
    allowedToolCategories: ['visual', 'verification'],
    readWrite: 'write',
    verificationRequirements: ['Before/after evidence required'],
  },
]
